# For every commit or tag that is pushed, but image from it and push this to docker hub

name: Deploy Docker Image

on:
  push:
  create:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      # Check out the code
      - uses: actions/checkout@v2

      - name: Docker meta (labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: partnersinhealth/pihemr-smoke-tests

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: pihci
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

        # Perform docker build and push on openmrs-server
      - name: Build/Push docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: partnersinhealth/pihemr-smoke-tests:latest
          labels: ${{ steps.meta.outputs.labels }}